# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Selenium Demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome 
      uses: browser-actions/setup-chrome@v1  

    - name: Xvfb
      run: | 
            export DISPLAY=:15.0
            Xvfb :15 -screen 0 1920x1080x24 > /dev/null 2>&1 &
            touch ~/.Xauthority
            xauth list
            fluxbox &
    
    - name: Run tests
      run:  mvn test -X